# Site settings
title: Kshitiz Sharma
email: kshitiz.sharma38@gmail.com
description: "Kshitiz Sharma's Portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/sharmakshitiz/
  - title: github
    url: http://github.com/ktzsh

# Postal address (add as many lines as necessary)
address:
  - line: Ajmer
  - line: Rajasthan, IN 305001

# Build settings
markdown: kramdown
permalink: pretty
