# Site settings
title: Kshitiz Sharma
email: kshitiz.sharma38@gmail.com
description: "Kshitiz Sharma's Portfolio"

# Postal address
address:
  - line: Adarsh Nagar, Ajmer
  - line: Rajasthan, IN 305001


# Hero Section
slider:
  - heading: "Hi! I'm Kshitiz Sharma"
    sub_heading: "Data Scientist and Innovator."
  - heading: "I am a working professional, pursuing his passion for
              Technology and Arts."
    sub_heading: "With an adaptive mind and broad perspective I love facing
                  challenging problems and looking for elegant solutions."
  - heading: 'Take a look at my
                <a class="smoothscroll" href="#experience" title="experience">CAREER PATH</a>
                and some of
                <a class="smoothscroll" href="#portfolio" title="portfolio">MY CREATIVE WORK</a>
                or
                <a class="smoothscroll" href="#contact" title="contact us">GET IN TOUCH</a>.'
    sub_heading: "My works vary from technical engineering projects to mind
                  refreshing artworks."


# About Section
org: VMock India Pvt. Ltd.
job: Principal Data Scientist
org_url: https://www.vmock.com
about: "With an adaptive mind and broad perspective I love facing challenging problems and looking for 
        creative solutions. Currently pursuing my passion for Technology and Arts. My dream is to be a 
        part of a technological breakthrough that has the potential to impact billion of lives."


# Education Section
education:
  - img: "img/about/1.jpg"
    date: "2014 - 2018"
    university: "Indian Institue of Technology (IIT), Delhi, IN"
    degree: "B.Tech. in Mathematics and Computing"
    content:
      - line: B.Tech. Project, Autonomous Object Tracking with UAVs
      - line: Summer Research Student, Object Detection and Tracking for Driverless cars
      - line: Web Management Coordinator, Alumni Affairs & International Programmes (AAIP)
      - line: Fine Arts and Crafts Club (FAC) Representative, Zanskar Hostel
      - line: Hockey and Athletics 
  - img: "img/about/2.jpg"
    date: "2012 - 2014"
    university: "D.A.V. Public School, Kota, IN"
    degree: "A.I.S.S.C.E - Science (Mathematics)"
    content:
      - line: Obtained 92.8% in All India Senior School Certificate Examination conducted by C.B.S.E.
  - img: "img/about/3.jpg"
    date: "2012"
    university: "Mayoor School, Ajmer, IN"
    degree: "A.I.S.S.E"
    content:
      - line: Obtained GPA of 10/10.


# Skills Section
skills:
  - title: MACHINE LEARNING FRAMEWORK
    list: "Tensorflow & Keras &bull; PyTorch <br />
          ONNX &bull; DeepSpeed &bull; Hugging Face<br />
          Nvidia Triton &bull; OpenCV &bull;"
  - title: PROGRAMMING LANGUAGES
    list: "Python &bull; C/C++ &bull; Java &bull; OCaml <br />
          CUDA &bull; OpenMP/MPI  &bull; LaTeX &bull; ONNXjs<br />
           Golang &bull; Android Application Development <br />"
  - title: PLATFORM, TOOLS AND LIBRARIES
    list: "MLFlow &bull; DVC &bull; Kubernetes <br />
          Celery &bull; Redis &bull; AWS SQS &bull; Git <br />
          AWS ECS &bull; AWS Fargate &bull; Docker <br />
          AWS Sagemaker &bull; AWS Opensearch &bull; New Relic <br />
          SQLAlchemy &bull; MongoDB"
  - title: WEB, VFX, 3D, DESIGN
    list: "HTML &bull; CSS &bull; PHP &bull; JS &bull; JQuery <br />
          Laravel &bull; Bootstrap &bull; Web2py<br />
          Jekyll &bull; Github Pages<br />
          Adobe Photoshop &bull; After Effects &bull; Macromedia Flash<br />
          Autodesk Maya &bull; Inventor &bull; AutoCAD<br />"


# Experience Section
experience:
  - img: "img/about/4.png"
    date: "July 2018 - Present"
    organization: "VMock India Pvt. Ltd., Gurgaon, IN"
    organization_description: "Career Analytics Platform powered by AI, revolutionizing the candidate-employer-university dynamics. Delivering a comprehensive suite of services including career coaching, instant feedback, intelligent hiring tools, smart editors, and career analytics. Empowering clients with a one-stop platform for unparalleled career success."
    multiple:
      - title: Principal Data Scientist (September 2021 - Present)
        description: "Managed cross-functional Data Science teams (15 Data Scientists & Data Analysts) across business verticals, providing technical and stakeholder management and contributing to research and development of data driven solutions. Mentored teams working on diverse data science problems, including Ranking, Search, Retrieval, Analytics, Entity Recognition (NER), Large Language Models (LLMs), Language Generation (NLG), Grammar Correction (GEC), Computer Vision, Recommendation Systems and Ontologies."
        content:
        - line: "Restructured Data Science teams and streamlined machine learning development cycle using MLFLow, AWS Sagemaker, EKS, resulting in 20-40% improvements in lead and cycle times."
        - line: "Implemented containerization of machine learning applications, CI/CD Pipelines, Application Performance Monitoring (APM) & Code Inspection tools, Load Metrics, QA Automations for fault-tolerant and scalable systems thereby reducing infrastructure cost by over 50% for data science teams."
        - line: "Mentored team in developing an in-house speech transcription pipeline with VAD (Voice Activity Detection), ASR (Speech Recognition), and Forced Alignment for word level timestamps, saving over few thousands USD/month on 3rd party external APIs and achieving a 29% reduction in word error rates."
        - line: "Strategized new initiatives like BestMatch for intelligent hiring with explainable FitScores and SMART Interviews for in person interview practice featuring both verbal and non-verbal feedback."
        - line: "Developed a chatbot for VMock utilizing OpenSearch as a vector database and GPT3.5 API, showcasing conversational process similar to LangChain."
      - title: Senior Data Scientist (December 2019 - September 2021)
        description: "Supervised a team of 3 people overseeing all research, development, reviews and deployment for the Resume Parser, powering the flagship Resume Product used across more than 130+ Countries and in leading Educational Institutes such as CMU, Stanford, Chicago Booth, University of Oxford, Columbia, Kellogg, INSEAD etc."
        content:
        - line: "Launched multilingual parsing capability, solving the Reverse Translation and Token Alignment problem using unsupervised IBM Model 1 and HMM models."
        - line: "Created an in-house Joint Machine Translation and Token Alignment system with a Transformer-based encoder-decoder model, achieving a 44 BLEU Score and a 7 AER."
        - line: "Engineered a highly efficient event-driven task-queue architecture for the Resume Parser, leveraging tools like Celery, Redis, and SNS, significantly reducing infrastructure costs and job fail rates."
        - line: "Implemented a high-speed N-gram super-section classifier with outstanding performance, boasting an impressive 81% top-1 accuracy and an exceptional 95% top-3 accuracy."
        - line: "Finetuned encoder LMs (BERT, RoBERTa) using PyTorch and Hugging Face for superior classification and entity recognition achieving 5-12% improvement over BiLSTM-CRF on various datasets."
      - title: Data Scientist (July 2018 - December 2019)
        description: "Improved and maintained a robust resume parser that required converting unstructured data into structured data and extracting useful information using techniques of NLP."
        content:
        - line: "Trained in-house BiLSTM-CRF based NERs with Character Embeddings and Attention Mechanism delivering high recall and precision (>92 % F1 Score) for recognizing various entities as positions, organizations, locations, universities, degrees, section titles etc."
        - line: "Executed the migration of a complex codebase of ~50,000 lines from Python2 to Python3, ensuring compatibility and eliminating deprecated features, resulting in enhanced performance and maintainability."
  - img: "img/about/5.png"
    date: "May 2017 - July 2017"
    organization: "Artifacia, Bangalore, IN"
    organization_description: ""
    single:
      - title: Research Intern (ML)
        content:
        - line: Implemented a Machine Learning algorithm using VGG16 ConvNet to extract image features and a LSTM-based recurrent layer for label predictions, achieving a significant 5-6% improvement over the company's best model.
        - line: Designed a text and vector similarity algorithm to filter Instagram images based on user text query and hashtags, incorporating 3rd party image tagging API and user-created hashtags for enhanced accuracy.
  - img: "img/about/6.jpg"
    date: "May 2016 - December 2018"
    organization: "Indian Institue of Technology (IIT), Delhi, IN"
    organization_description: ""
    multiple:
      - title: "B.Tech. Project: Autonomous Object Tracking With Uavs"
        content:
        - line: "Developed an advanced autonomous agent using computer vision and deep reinforcement learning techniques, including Q-Learning algorithms and experience replay for real-world object tracking."
        - line: "Utilized a drone and realistic physics simulations to track a moving car, leveraging a customized version of Microsoft AirSim Simulator for training and testing."
      - title: "Summer Research Intern: Object Detection And Tracking For Driverless Cars"
        content:
        - line: "Evaluated Object Detection and Tracking models such as region proposal based classification R-CNN models (Fast, Faster R-CNN) as well as regression based models such as YOLO for detection."
        - line: "Utilized detection models and LSTMs to extract features, generate heatmaps, and handle occlusions for robust tracking in sequences/videos."


# Portfolio Sectionn
portfolio:
  three_row:
    - thumbnail: "img/portfolio/artwork/collage.png"
      heading: Sketching
      subheading: Free-hand Sketching
      modal_id: "#portfolioModal1"
    - thumbnail: "img/portfolio/3dmodel/1.png"
      heading: 3D Modelling
      subheading: AutoDesk Maya
      modal_id: "#portfolioModal2"
    - thumbnail: "img/portfolio/houseday/collage.png"
      heading: House Day Decoration
      subheading: Themed Event
      modal_id: "#portfolioModal3"
  two_row:
    - thumbnail: "img/portfolio/videos/sample.png"
      heading: Animation and Video Editing
      subheading: Adobe Flash and Video Editors
      modal_id: "#portfolioModal4"
    - thumbnail: "img/portfolio/website/sample.png"
      heading: Web Design and Development
      subheading: Jekyll, HTML, CSS, Javascript
      modal_id: "#portfolioModal5"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 000


# Social Links
social:
  - title: github
    url: http://github.com/ktzsh
  - title: linkedin
    url: https://www.linkedin.com/in/sharmakshitiz/


# Google Analytics
google_analytics: UA-207899879-1

# Build settings
markdown: kramdown
permalink: pretty
