# Site settings
title: Kshitiz Sharma
email: kshitiz.sharma38@gmail.com
description: "Kshitiz Sharma's Portfolio"

# Postal address
address:
  - line: Adarsh Nagar, Ajmer
  - line: Rajasthan, IN 305001


# Hero Section
slider:
  - heading: "Hi! I'm Kshitiz Sharma"
    sub_heading: "Data Scientist and Innovator."
  - heading: "I am a working professional, pursuing his passion for
              Technology and Arts."
    sub_heading: "With an adaptive mind and broad perspective I love facing
                  challenging problems and looking for elegant solutions."
  - heading: 'Take a look at my
                <a class="smoothscroll" href="#experience" title="experience">CAREER PATH</a>
                and some of
                <a class="smoothscroll" href="#portfolio" title="portfolio">MY CREATIVE WORK</a>
                or
                <a class="smoothscroll" href="#contact" title="contact us">GET IN TOUCH</a>.'
    sub_heading: "My works vary from technical engineering projects to mind
                  refreshing artworks."


# About Section
org: VMock India Pvt. Ltd.
job: Principal Data Scientist
org_url: https://www.vmock.com
about: "With an adaptive mind and broad perspective I love facing challenging problems and looking for 
        creative solutions. Currently pursuing my passion for Technology and Arts. My dream is to be a 
        part of a technological breakthrough that has the potential to impact billion of lives."


# Education Section
education:
  - img: "img/about/1.jpg"
    date: "2014 - 2018"
    university: "Indian Institue of Technology (IIT), Delhi, IN"
    degree: "B.Tech. in Mathematics and Computing"
    content:
      - line: B.Tech. Project, Autonomous Object Tracking with UAVs
      - line: Summer Research Student, Object Detection and Tracking for Driverless cars
      - line: Web Management Coordinator, Alumni Affairs & International Programmes (AAIP)
      - line: Fine Arts and Crafts Club (FAC) Representative, Zanskar Hostel
  - img: "img/about/2.jpg"
    date: "2012 - 2014"
    university: "D.A.V. Public School, Kota, IN"
    degree: "A.I.S.S.C.E - Science (Mathematics)"
    content:
      - line: Obtained 92.8% in All India Senior School Certificate Examination conducted by C.B.S.E.
  - img: "img/about/3.jpg"
    date: "2012"
    university: "Mayoor School, Ajmer, IN"
    degree: "A.I.S.S.E"
    content:
      - line: Obtained GPA of 10/10.


# Skills Section
skills:
  - title: MACHINE LEARNING FRAMEWORK
    list: "Tensorflow & Keras &bull; PyTorch &bull; Caffe<br />
          ONNX &bull; DeepSpeed &bull; Hugging Face<br />
          Darknet &bull; OpenCV &bull; Matlab"
  - title: PROGRAMMING
    list: "Python &bull; C/C++ &bull; Java &bull; OCaml <br />
          CUDA &bull; Golang &bull; LaTeX<br />
          Android Application Development <br />"
  - title: PLATFORM, TOOLS AND OTHER LIBRARIES
    list: "MLFlow &bull; DVC &bull; AWS Console <br />
          Celery &bull; Redis &bull; AWS SQS &bull; Git <br />
          Docker &bull; Kubernetes <br />
          SQLAlchemy &bull; MongoDB"
  - title: WEB, VFX, 3D, DESIGN
    list: "HTML &bull; CSS &bull; PHP &bull; JS &bull; JQuery <br />
          Laravel &bull; Bootstrap &bull; Web2py<br />
          Jekyll &bull; Github Pages<br />
          Adobe Photoshop &bull; After Effects &bull; Macromedia Flash<br />
          Autodesk Maya &bull; Inventor &bull; AutoCAD<br />"


# Experience Section
experience:
  - img: "img/about/4.png"
    date: "July 2018 - Present"
    organization: "VMock India Pvt. Ltd., Gurgaon, IN"
    multiple:
      - title: Principal Data Scientist (July 2021 - Present)
        content:
        - line: Led all Data Science teams at VMock across all business verticals contributing to Technical Management and R&D processes.
                Transformed the organizaion strucutre of Data Science teams, implemented Monorepo and MLOps practices using MLFLow and DVC. 
        - line: Managed research team working on standardizing SOTA research to train and make large scale transformer models 
                productionable using onnxruntime, deepspeed integrations, mixed precision training, quatization and gradient accumulation.
                Subsequently adopted these models across various NLP problems within the company.
      - title: Senior Data Scientist (December 2019 - July 2021)
        content:
        - line: "Led a team of 3 people overseeing all reviews, development, improvements, deployment and research projects for the Resume Parser Product."
        - line: "Deployed production ready prediction models with Tensorflow Serving and implemented Async. Task Queue pipeline using Celery and AWS SQS."
        - line: "Tasked with developing a multilingual parser capable of parsing resumes in French Language. Solved the Reverse Translation and 
                Token Alignment problem using unsupervised IBM Model 1 and HMM models like Berkeley Aligner and string-matching heuristics using Levenshtein distance."
        - line: "Worked on developing an in-house Joint Machine Translation and Token Alignment system using Mbart Transformer based encoder-decoer model."
      - title: Data Scientist (July 2018 - December 2019)
        content:
        - line: "Tasked with improving and maintaining a robust resume parser that required converting unstructured data into
                structured data and extracting useful information using techniques of NLP."
        - line: "Trained in-house BiLSTM CRF based NERs with Character Embeddings and Attention Mechanism 
                delivering high recall and precision for recognizing various entities as positions, organizations, locations, universities, 
                degrees, section titles etc."
        - line: "Built an unsupervised model using topic modeling technique LLDA and PLDA for fast super-section mappings in resume."
  - img: "img/about/5.png"
    date: "May 2017 - July 2017"
    organization: "Artifacia, Bangalore, IN"
    single:
      - title: Research Intern (ML)
        content:
        - line: Media Engagement Prediction - Predicting engagement (likes) on Instagram posts.
        - line: Visual Recognition - Identifying objects and concepts in images to assign hashtags.
        - line: Implemented Convolution Neural Network (CNN) and Recurrent Neural Network (RNN) Models for these problems in Keras and Tensorflow.
  - img: "img/about/6.jpg"
    date: "May 2016 - December 2018"
    organization: "Indian Institue of Technology (IIT), Delhi, IN"
    multiple:
      - title: "B.Tech. Project: Autonomous Object Tracking with UAVs"
        content:
        - line: "Developed an autonomous agent capable of tracking an object using techniques of Computer Vision and Deep Reinforcement Learning. 
                Used Microsoft AirSim Simulator where a Drone was the tracker and a Car acted as an object to be tracked."
      - title: "Summer Research Intern: Object Detection and Tracking for Driverless Cars"
        content:
        - line: "Developed a system to tackle the problem of object detection and tracking using computer vision and machine 
                learning techniques. We explored slower region proposal based classification models (R-CNN and its variants 
                - Fast, Faster R-CNN), and faster end-to-end regression based models (such as YOLO) for detection."
        - line: "Subsequently, we used detection models for feature extraction and generating detection heatmaps along with 
                LSTMs (Long Short Term Memory) to capture temporal information in sequences/videos for robust tracking and occlusion handling."


# Portfolio Sectionn
portfolio:
  three_row:
    - thumbnail: "img/portfolio/artwork/collage.png"
      heading: Sketching
      subheading: Free-hand Sketching
      modal_id: "#portfolioModal1"
    - thumbnail: "img/portfolio/3dmodel/1.png"
      heading: 3D Modelling
      subheading: AutoDesk Maya
      modal_id: "#portfolioModal2"
    - thumbnail: "img/portfolio/houseday/collage.png"
      heading: House Day Decoration
      subheading: Themed Event
      modal_id: "#portfolioModal3"
  two_row:
    - thumbnail: "img/portfolio/videos/sample.png"
      heading: Animation and Video Editing
      subheading: Adobe Flash and Video Editors
      modal_id: "#portfolioModal4"
    - thumbnail: "img/portfolio/website/sample.png"
      heading: Web Design and Development
      subheading: Jekyll, HTML, CSS, Javascript
      modal_id: "#portfolioModal5"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 000


# Social Links
social:
  - title: github
    url: http://github.com/ktzsh
  - title: linkedin
    url: https://www.linkedin.com/in/sharmakshitiz/


# Build settings
markdown: kramdown
permalink: pretty
